### ISSUE TITLE
Cannot read property 'writable' of undefined

### ISSUE THREAD

**Issue by nbdelorme** [ChrisLahaye/pm2-messages#5]
Not a pm2-messages issue, but significant enough to mention here. pm2-messages is vulnerable to [pm2 bug 4627](https://github.com/Unitech/pm2/issues/4627).

We've had to disable pm2-messages because pm2 keeps crashing/restarting when being scraped by multiple prometheus servers.

@ChrisLahaye I'd would love to know your thoughts on this issue or if you have ideas for a solution.

**Comment by aldipower** [comment]
We have _exactly_ the same thing and setup as you describe and pm2 is crashing by it.

**Comment by ChrisLahaye** [comment]
Can you guys please report the pm2 and OS version, then I will have a look.

**Comment by aldipower** [comment]
Hi, thank you. :)

PM2 version: 4.4.0
Node.js version: 12.16.2
OS: Ubuntu 19.10

Here is also some log output
https://github.com/Unitech/pm2/issues/4627#issuecomment-642983109

**Comment by ChrisLahaye** [comment]
@aldipower @nbdelorme I had a look at the issue but wasn't able to fix it.
According to my observations this error only occurs when two processes are requesting / have opened the bus, and one of the two finishes / closes the bus while the other one is still active. 

We can work around this issue by not disconnecting from pm2 after having received the messages. The complication is that the main process will not properly exit due to open handles, so we cannot use this as default.

So I propose to:
- Add a `close` method to manually disconnect from pm2 when you would like your process to exit
- Add a configuration option to not disconnect after every request, meaning you will be doing this explicitly

Thoughts?

**Comment by aldipower** [comment]
Hi @ChrisLahaye !
Thanx for watching and investigating!

This is reasonable to me. 
I am a fan of calling "close()" manually anyway. We are doing this at a lot of cleanup places in our worker and cluster conglomerate, so this isn't a problem and I like it to have it explicit.

IMHO your proposal isn't a workaround, it's a real fix to correct things, like they should have from the beginning.
I would go as far to state out and make the new behavior as the default.
Make "configuration option to not disconnect after every request" as the default.
But I would be fine with everything this is just my preferred option.

Have a nice day! 
:)

**Comment by ChrisLahaye** [comment]
@aldipower The pm2 library doesn't provide a lot of options to properly track connection state and errors, therefore, I initially went to connect and disconnect each request. Each connect results in a new socket, therefore they would need to be tracked to avoid a leak. 

My concern is that if connect and disconnect need to happen explicitly, that in case of errors, e.g. disconnecting (not sure if this can happen with a file socket), we would be unable to detect this and reconnect when needed. Maybe we should just abstract away from this and expose basic connect and disconnect methods.

Thoughts?

**Comment by aldipower** [comment]
Hey @ChrisLahaye !
Tbh, I have no clue, what would work best here. :smile: 
But I would be totally ok with just to have basic connect and disconnect methods.

**Comment by ChrisLahaye** [comment]
@aldipower @nbdelorme I just released version 4.0.0 with basic `connect` and `disconnect` methods. Check the `README.md` for a proper example. I also ran some concurrency tests confirming that version 4 fixes the issue.

Looking forward to hear from you guys

**Comment by nbdelorme** [comment]
@ChrisLahaye apologies for the wait. We've promoted your latest changes to a few environments and are monitoring carefully. Being a little more cautious this time. So far so good. I'll confirm once we are confident things are stable in production. Big thanks for addressing this issue.

**Comment by aldipower** [comment]
Hey @ChrisLahaye , thanx a lot for addressing this. This is great. We will test this in the near future and give you feedback then.

**Comment by ChrisLahaye** [comment]
@nbdelorme @aldipower Have all issues been solved now?

**Comment by nbdelorme** [comment]
@ChrisLahaye things looked good when we tested for a few hours, but we had to temporarily disable. The new code is causing some undesired side-effect on windows development machines (where we don't run pm2 ...). Everything seemed to be working correctly on linux + pm2. Feel free to close and I'll reach out again if needed.

As before, thanks for your amazing support.
