### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by nbdelorme** [ChrisLahaye/pm2-messages#7]
@ChrisLahaye hello again. For a little context, your pm2-messages is being used in CoStar Group's flagship product CoStar Suite.

We ended up having to disable prometheus scraping in production because of a memory leak. 
![image](https://user-images.githubusercontent.com/5318775/91983224-60025980-ecf9-11ea-92f0-0269828b71a6.png)

This leak was traced back to pm2-messages. The leak is of an object containing pendingBusTargets, resolverBusTargets, and messages as you can see in this screenshot. A thorough memory analysis was performed to discover and confirm these findings.
![image](https://user-images.githubusercontent.com/5318775/91983292-76a8b080-ecf9-11ea-902f-c0007e48a697.png)

A thorough analysis of the code confirmed that the leak is of the myBus Listener (myBus.on).

The following PR suggests a remedy by allowing the bus listeners to be destroyed after use.
https://github.com/ChrisLahaye/pm2-messages/pull/8

**Comment by nbdelorme** [comment]
all code change credit goes to @hkmushtaq

**Comment by ChrisLahaye** [comment]
Hi @nbdelorme, thank you for investigating this. I was wondering, are you still planning on making a pull request, else I will make the changes myself.

**Comment by nbdelorme** [comment]
Pull request is [here ](https://github.com/ChrisLahaye/pm2-messages/pull/8)... looks like I somehow closed it several days ago. My bad. My github skills are clearly not that sharp.

**Comment by nbdelorme** [comment]
This graph shows well how dramatic the change is.
![image](https://user-images.githubusercontent.com/5318775/92934552-9d5f9900-f415-11ea-9f11-2f8834143379.png)

**Comment by ChrisLahaye** [comment]
@nbdelorme I have merged your pull request, many thanks! I further improved on two aspects:
- Bus listener key-value pairs weren't explicitly cleaned up. Keys are randomly generated and their values (bus listeners) were being set to null when all messages have been received, this still results in an constantly growing structure.
- Bus listeners weren't cleaned up when a request expired.

Could you please test the latest version on GitHub and confirm whether everything is okay. After confirmation I will do an npm release.

**Comment by ChrisLahaye** [comment]
@nbdelorme I released 4.0.2 on npm

**Comment by nbdelorme** [comment]
Thanks @ChrisLahaye this works. My sprint just ended and was going to look at this next. I'm happy to consume 4.0.2 without revision. I have full confidence. Thanks!
